import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { listGames, getGame } from '../src/lib/catalog.ts';
import { resolveLaunch } from '../src/lib/launch.ts';
import { isSafeRelativePath, validateManifest } from '../src/lib/manifest.ts';
const fixture=JSON.parse(readFileSync(new URL('../contracts/game-manifest.example.json',import.meta.url),'utf8'));
test('catalog exposes three explicitly demo/concept fixtures',()=>{assert.equal(listGames().length,3);assert.ok(listGames().every(g=>g.status==='demo'||g.status==='concept'));});
test('search matches title and trims whitespace',()=>assert.equal(listGames(' 午夜 ').length,1));
test('genre filter works',()=>assert.equal(listGames('','都市')[0].slug,'after-rain'));
test('unknown game returns undefined',()=>assert.equal(getGame('missing'),undefined));
test('empty search returns no matching fixtures',()=>assert.equal(listGames('not-found').length,0));
test('trusted demo can launch',()=>assert.deepEqual(resolveLaunch({gameId:'midnight-letter',edition:'demo'}),{status:200,body:{src:'/demo/index.html',mode:'trusted-smoke-demo'}}));
test('paid flag cannot authorize full edition',()=>assert.equal(resolveLaunch({gameId:'midnight-letter',edition:'full',paid:true}).status,503));
test('concept has no runnable demo',()=>assert.equal(resolveLaunch({gameId:'after-rain',edition:'demo'}).status,404));
test('unknown ID is rejected',()=>assert.equal(resolveLaunch({gameId:'missing',edition:'demo'}).status,404));
test('invalid requests are rejected',()=>{for(const v of [null,[],{},'x',{gameId:'midnight-letter',edition:['demo']},{gameId:9,edition:'demo'},{gameId:'midnight-letter',edition:'preview'}])assert.equal(resolveLaunch(v).status,400);});
test('known manifest structure is accepted, not a release approval',()=>assert.deepEqual(validateManifest(fixture),[]));
for(const path of ['../index.html','/index.html','a/../../x','https://example.com/x','a\\b','%2e%2e/x','a//x','a/./b','a/',''])test(`unsafe path rejected: ${path}`,()=>assert.equal(isSafeRelativePath(path),false));
test('simple asset path is accepted',()=>assert.ok(isSafeRelativePath('assets/scene-01.webp')));
test('duplicate asset is rejected',()=>assert.ok(validateManifest({...fixture,assets:[...fixture.assets,...fixture.assets]}).some(x=>x.includes('duplicate'))));
test('case collision is rejected',()=>assert.ok(validateManifest({...fixture,assets:[...fixture.assets,{...fixture.assets[0],path:'INDEX.html'}]}).some(x=>x.includes('duplicate'))));
test('missing entry is rejected',()=>assert.ok(validateManifest({...fixture,entry:'other.html'}).some(x=>x.includes('entry missing'))));
test('external entry is rejected',()=>assert.ok(validateManifest({...fixture,entry:'https://example.com/index.html'}).length));
test('private files are rejected',()=>assert.ok(validateManifest({...fixture,assets:[...fixture.assets,{...fixture.assets[0],path:'.env'}]}).some(x=>x.includes('private'))));
test('malformed checksum rejected',()=>assert.ok(validateManifest({...fixture,assets:[{...fixture.assets[0],sha256:'bad'}]}).some(x=>x.includes('checksum'))));
test('negative sizes rejected',()=>assert.ok(validateManifest({...fixture,assets:[{...fixture.assets[0],bytes:-1}]}).some(x=>x.includes('size'))));
test('unrecognized engine rejected',()=>assert.ok(validateManifest({...fixture,engine:'arbitrary-code'}).length));
test('unversioned manifest rejected',()=>assert.ok(validateManifest({...fixture,schemaVersion:2}).length));
test('invalid save version rejected',()=>assert.ok(validateManifest({...fixture,saveVersion:0}).length));
test('oversized asset rejected',()=>assert.ok(validateManifest({...fixture,assets:[{...fixture.assets[0],bytes:2**30}]}).some(x=>x.includes('size'))));
